window.API_BASE = (typeof window !== "undefined" && window.FORGEX_API_BASE) || "http://localhost:8002";

window.Ic = {
  logo: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 36 36", fill: "none" }), React.createElement("rect", { width: "36", height: "36", rx: "10", fill: "#2f6bff" }), React.createElement("path", { d: "M10 26V14l8-6 8 6v12H18v-6h-4v6h-4z", fill: "#fff" })); },
  arrow: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 16 16", fill: "none" }), React.createElement("path", { d: "M6 3l5 5-5 5", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" })); },
  sparkle: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 14 14", fill: "none" }), React.createElement("path", { d: "M7 0l1.5 4.5L13 6l-4.5 1.5L7 12l-1.5-4.5L1 6l4.5-1.5L7 0z", fill: "currentColor" })); },
  trendUp: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 22 22", fill: "none" }), React.createElement("path", { d: "M2 18L8 12L12 16L20 6", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }), React.createElement("path", { d: "M15 6H20V11", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" })); },
  shield: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 22 22", fill: "none" }), React.createElement("path", { d: "M11 2L3 6V11C3 16.5 7.5 20.5 11 22C14.5 20.5 19 16.5 19 11V6L11 2Z", fill: "currentColor", opacity: "0.2" }), React.createElement("path", { d: "M11 2L3 6V11C3 16.5 7.5 20.5 11 22C14.5 20.5 19 16.5 19 11V6L11 2Z", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round", "stroke-linejoin": "round" }), React.createElement("path", { d: "M9 11L10.5 12.5L13 9.5", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round", "stroke-linejoin": "round" })); },
  wrench: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 22 22", fill: "none" }), React.createElement("path", { d: "M14.7 1.3L11.3 4.7C10.9 5.1 10.9 5.7 11.3 6.1L15.9 10.7C16.3 11.1 16.9 11.1 17.3 10.7L20.7 7.3", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round", "stroke-linejoin": "round" }), React.createElement("path", { d: "M1 17L5 13L8 16L12 12", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round", "stroke-linejoin": "round" })); },
  calendar: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 22 22", fill: "none" }), React.createElement("rect", { x: "2", y: "4", width: "18", height: "16", rx: "2", stroke: "currentColor", "stroke-width": "1.5" }), React.createElement("path", { d: "M2 8H20", stroke: "currentColor", "stroke-width": "1.5" }), React.createElement("path", { d: "M7 2V5", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" }), React.createElement("path", { d: "M15 2V5", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" })); },
  chat: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 22 22", fill: "none" }), React.createElement("path", { d: "M19 3H3C2.4 3 2 3.4 2 4V16C2 16.6 2.4 17 3 17H7L11 21L15 17H19C19.6 17 20 16.6 20 16V4C20 3.4 19.6 3 19 3Z", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round", "stroke-linejoin": "round" })); },
  home: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 22 22", fill: "none" }), React.createElement("path", { d: "M3 9L11 3L19 9V19C19 19.6 18.6 20 18 20H6C5.4 20 5 19.6 5 19V9Z", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round", "stroke-linejoin": "round" })); },
  dollar: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 22 22", fill: "none" }), React.createElement("circle", { cx: "11", cy: "11", r: "9", stroke: "currentColor", "stroke-width": "1.5" }), React.createElement("path", { d: "M11 6V16", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" }), React.createElement("path", { d: "M8 9H13C13.6 9 14 9.4 14 10V11C14 11.6 13.6 12 13 12H9C8.4 12 8 12.4 8 13V14C8 14.6 8.4 15 9 15H14", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" })); },
  person: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 24 24", fill: "none" }), React.createElement("circle", { cx: "12", cy: "8", r: "4", stroke: "currentColor", "stroke-width": "1.5" }), React.createElement("path", { d: "M4 20C4 16.7 7.6 14 12 14C16.4 14 20 16.7 20 20", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" })); },
  chevron: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 18 18", fill: "none" }), React.createElement("path", { d: "M7 4L12 9L7 14", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" })); },
  sliders: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 22 22", fill: "none" }), React.createElement("path", { d: "M4 18V12", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" }), React.createElement("path", { d: "M4 8V4", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" }), React.createElement("circle", { cx: "4", cy: "10", r: "2", stroke: "currentColor", "stroke-width": "1.5" }), React.createElement("path", { d: "M11 18V10", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" }), React.createElement("path", { d: "M11 6V4", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" }), React.createElement("circle", { cx: "11", cy: "8", r: "2", stroke: "currentColor", "stroke-width": "1.5" }), React.createElement("path", { d: "M18 18V14", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" }), React.createElement("path", { d: "M18 10V4", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" }), React.createElement("circle", { cx: "18", cy: "12", r: "2", stroke: "currentColor", "stroke-width": "1.5" })); },
  chevronsRight: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 22 22", fill: "none" }), React.createElement("path", { d: "M8 7L13 11L8 15", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" }), React.createElement("path", { d: "M13 7L18 11L13 15", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round" })); },
  logout: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 18 18", fill: "none" }), React.createElement("path", { d: "M10 3H3V15H10", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round", "stroke-linejoin": "round" }), React.createElement("path", { d: "M8 9H16", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round" }), React.createElement("path", { d: "M13 6L16 9L13 12", stroke: "currentColor", "stroke-width": "1.5", "stroke-linecap": "round", "stroke-linejoin": "round" })); },
  plus: function(p) { return React.createElement("svg", Object.assign({}, p, { viewBox: "0 0 18 18", fill: "none" }), React.createElement("path", { d: "M9 3V15", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round" }), React.createElement("path", { d: "M3 9H15", stroke: "currentColor", "stroke-width": "2", "stroke-linecap": "round" })); },
};
